from .UNet import EUnet
from .ResUNet import Resnet34_Unet
from .UNetPlusPlus import UnetPlusPlus
from .dsNet import DSNet
from .punet import PUnet
from .msanet import MSANET
from .PSPNet import PSPNet
from .linknet import LinkNet
from .deeplabv3_plus import DeepLab
